CREATE TABLE categories (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at  TIMESTAMP(6) NOT NULL,
    updated_at  TIMESTAMP(6) NOT NULL,
    description VARCHAR(500),
    is_active   BOOLEAN      NOT NULL,
    name        VARCHAR(150) NOT NULL,
    slug        VARCHAR(150) NOT NULL,
    parent_id   BIGINT,
    CONSTRAINT UKoul14ho7bctbefv8jywp5v3i2 UNIQUE (slug),
    CONSTRAINT FKsaok720gsu4u2wrgbk10b5n8d FOREIGN KEY (parent_id) REFERENCES categories(id)
);

CREATE TABLE products (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at      TIMESTAMP(6)   NOT NULL,
    updated_at      TIMESTAMP(6)   NOT NULL,
    cost            NUMERIC(38,2),
    description     TEXT,
    image_public_id VARCHAR(200),
    image_url       VARCHAR(500),
    is_active       BOOLEAN        NOT NULL,
    is_available    BOOLEAN        NOT NULL,
    name            VARCHAR(200)   NOT NULL,
    price           NUMERIC(38,2)  NOT NULL,
    sku             VARCHAR(100),
    slug            VARCHAR(200)   NOT NULL,
    category_id     BIGINT         NOT NULL,
    CONSTRAINT UKfhmd06dsmj6k0n90swsh8ie9g UNIQUE (sku),
    CONSTRAINT FKog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE INDEX idx_products_category_id ON products(category_id);